[package]
name = "ingot-backtest"
version.workspace = true
edition.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
ingot-engine = { path = "../ingot-engine" }
ingot-connectivity = { path = "../ingot-connectivity" }
ingot-accounting = { path = "../ingot-accounting" }
ingot-core = { path = "../ingot-core" }
ingot-primitives = { path = "../ingot-primitives" }
chrono = { workspace = true }
rust_decimal = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
smol_str = { workspace = true }
tracing = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
rand = { workspace = true }

[dev-dependencies]
proptest = { workspace = true }
rust_decimal_macros = { workspace = true }
tokio = { workspace = true, features = ["test-util", "macros", "rt-multi-thread"] }
