services:
  timescaledb:
    image: timescale/timescaledb:latest-pg17
    container_name: ingot-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ingot_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      TS_TUNE_MEMORY: "2GB"
      TS_TUNE_NUM_CPUS: "4"
    volumes:
      - ingot_db_data:/var/lib/postgresql/data

volumes:
  ingot_db_data:
    name: ingot_db_data