[package]
name = "ingot-core"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
anyhow.workspace = true
chrono.workspace = true
ingot-primitives.workspace = true
rust_decimal.workspace = true
serde.workspace = true
serde_json.workspace = true
smol_str.workspace = true

[lints]
workspace = true

[dev-dependencies]
rust_decimal_macros = "1.40.0"
serde_json.workspace = true
